steps:
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 
           'us-central1-docker.pkg.dev/${PROJECT_ID}/appcare/agora-middleware', 
           '.']

  # Docker Push
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 
           'us-central1-docker.pkg.dev/${PROJECT_ID}/appcare/agora-middleware']

  # Deploy to Kubernetes
  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
    - run
    - --filename=deploy.yaml
    - --location=us-central1
    - --cluster=appcare