---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: gateway-rest
  name: gateway-rest
  namespace: default
spec:
  ports:
  - name: tcp
    port: 80
    targetPort: 3000
  selector:
    app: agora-middleware
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: agora-middleware
  name: agora-middleware
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agora-middleware
  template:
    metadata:
      labels:
        app: agora-middleware
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: agora-middleware
        image: us-central1-docker.pkg.dev/vital-valor-396603/appcare/agora-middleware:latest
        name: gateway-rest
        resources:
          limits:
            cpu: 250m
            ephemeral-storage: 500Mi
            memory: 512Mi
          requests:
            cpu: 250m
            ephemeral-storage: 500Mi
            memory: 512Mi
